# Site Settings
title: Philippe Bureau
description: 0 to Hero guides
email: pbureau@arista.com

# URL Settings (Crucial for user pages)
url: "https://philippebureau.github.io"
baseurl: "" # Keep this empty for a root user site!

# Theme Selection
remote_theme: abhinavs/moonwalk

# Core Moonwalk configuration
theme_config:
  appearance: "dark"
  appearance_toggle: true
  show_navbar: true
